# Site settings
baseurl: "/WebAppsDocs"
url: "http://MicrosoftEdge.github.io/WebAppsDocs"
repositoryurl: "https://github.com/MicrosoftEdge/WebAppsDocs/tree/master/"
landingurl: "/WebAppsDocs/en-US/win10/HWA.htm"
hacksterurl: "http://microsoft.hackster.io"
hardwareurl: "http://go.microsoft.com/fwlink/p/?linkID=532948"
signupurl: "https://www.windowsondevices.com/signup.aspx"
downloadurl: "http://connect.microsoft.com/windowsembeddedIoT/Downloads/"


# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: pretty
highlighter: pygments
safe: true
lsi: false
