//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahApps.Metro.Lang {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorNames() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MahApps.Metro.Lang.ColorNames", typeof(ColorNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Alice Blue.
        /// </summary>
        internal static string AliceBlue {
            get {
                return ResourceManager.GetString("AliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Antique White.
        /// </summary>
        internal static string AntiqueWhite {
            get {
                return ResourceManager.GetString("AntiqueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aqua.
        /// </summary>
        internal static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aquamarine.
        /// </summary>
        internal static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Azure.
        /// </summary>
        internal static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Beige.
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bisque.
        /// </summary>
        internal static string Bisque {
            get {
                return ResourceManager.GetString("Bisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Blanched Almond.
        /// </summary>
        internal static string BlanchedAlmond {
            get {
                return ResourceManager.GetString("BlanchedAlmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Blue Violet.
        /// </summary>
        internal static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Burly Wood.
        /// </summary>
        internal static string BurlyWood {
            get {
                return ResourceManager.GetString("BurlyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cadet Blue.
        /// </summary>
        internal static string CadetBlue {
            get {
                return ResourceManager.GetString("CadetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chartreuse.
        /// </summary>
        internal static string Chartreuse {
            get {
                return ResourceManager.GetString("Chartreuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chocolate.
        /// </summary>
        internal static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Coral.
        /// </summary>
        internal static string Coral {
            get {
                return ResourceManager.GetString("Coral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cornflower Blue.
        /// </summary>
        internal static string CornflowerBlue {
            get {
                return ResourceManager.GetString("CornflowerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cornsilk.
        /// </summary>
        internal static string Cornsilk {
            get {
                return ResourceManager.GetString("Cornsilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Crimson.
        /// </summary>
        internal static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Blue.
        /// </summary>
        internal static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Cyan.
        /// </summary>
        internal static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark EasyITCenterrod.
        /// </summary>
        internal static string DarkEasyITCenterrod {
            get {
                return ResourceManager.GetString("DarkEasyITCenterrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Gray.
        /// </summary>
        internal static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Green.
        /// </summary>
        internal static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Khaki.
        /// </summary>
        internal static string DarkKhaki {
            get {
                return ResourceManager.GetString("DarkKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Magenta.
        /// </summary>
        internal static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Olive Green.
        /// </summary>
        internal static string DarkOliveGreen {
            get {
                return ResourceManager.GetString("DarkOliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Orange.
        /// </summary>
        internal static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Orchid.
        /// </summary>
        internal static string DarkOrchid {
            get {
                return ResourceManager.GetString("DarkOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Red.
        /// </summary>
        internal static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Salmon.
        /// </summary>
        internal static string DarkSalmon {
            get {
                return ResourceManager.GetString("DarkSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Sea Green.
        /// </summary>
        internal static string DarkSeaGreen {
            get {
                return ResourceManager.GetString("DarkSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Slate Blue.
        /// </summary>
        internal static string DarkSlateBlue {
            get {
                return ResourceManager.GetString("DarkSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Slate Gray.
        /// </summary>
        internal static string DarkSlateGray {
            get {
                return ResourceManager.GetString("DarkSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Turquoise.
        /// </summary>
        internal static string DarkTurquoise {
            get {
                return ResourceManager.GetString("DarkTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dark Violet.
        /// </summary>
        internal static string DarkViolet {
            get {
                return ResourceManager.GetString("DarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Deep Pink.
        /// </summary>
        internal static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Deep Sky Blue.
        /// </summary>
        internal static string DeepSkyBlue {
            get {
                return ResourceManager.GetString("DeepSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dim Gray.
        /// </summary>
        internal static string DimGray {
            get {
                return ResourceManager.GetString("DimGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dodger Blue.
        /// </summary>
        internal static string DodgerBlue {
            get {
                return ResourceManager.GetString("DodgerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný EasyITCenterrod.
        /// </summary>
        internal static string EasyITCenterrod {
            get {
                return ResourceManager.GetString("EasyITCenterrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Firebrick.
        /// </summary>
        internal static string Firebrick {
            get {
                return ResourceManager.GetString("Firebrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Floral White.
        /// </summary>
        internal static string FloralWhite {
            get {
                return ResourceManager.GetString("FloralWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Forest Green.
        /// </summary>
        internal static string ForestGreen {
            get {
                return ResourceManager.GetString("ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Fuchsia.
        /// </summary>
        internal static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gainsboro.
        /// </summary>
        internal static string Gainsboro {
            get {
                return ResourceManager.GetString("Gainsboro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ghost White.
        /// </summary>
        internal static string GhostWhite {
            get {
                return ResourceManager.GetString("GhostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Green Yellow.
        /// </summary>
        internal static string GreenYellow {
            get {
                return ResourceManager.GetString("GreenYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Honeydew.
        /// </summary>
        internal static string Honeydew {
            get {
                return ResourceManager.GetString("Honeydew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hot Pink.
        /// </summary>
        internal static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Indian Red.
        /// </summary>
        internal static string IndianRed {
            get {
                return ResourceManager.GetString("IndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Indigo.
        /// </summary>
        internal static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ivory.
        /// </summary>
        internal static string Ivory {
            get {
                return ResourceManager.GetString("Ivory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Khaki.
        /// </summary>
        internal static string Khaki {
            get {
                return ResourceManager.GetString("Khaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lavender.
        /// </summary>
        internal static string Lavender {
            get {
                return ResourceManager.GetString("Lavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lavender Blush.
        /// </summary>
        internal static string LavenderBlush {
            get {
                return ResourceManager.GetString("LavenderBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lawn Green.
        /// </summary>
        internal static string LawnGreen {
            get {
                return ResourceManager.GetString("LawnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lemon Chiffon.
        /// </summary>
        internal static string LemonChiffon {
            get {
                return ResourceManager.GetString("LemonChiffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Blue.
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LightCoral.
        /// </summary>
        internal static string LightCoral {
            get {
                return ResourceManager.GetString("LightCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Cyan.
        /// </summary>
        internal static string LightCyan {
            get {
                return ResourceManager.GetString("LightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light EasyITCenterrod Yellow.
        /// </summary>
        internal static string LightEasyITCenterrodYellow {
            get {
                return ResourceManager.GetString("LightEasyITCenterrodYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Gray.
        /// </summary>
        internal static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Green.
        /// </summary>
        internal static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Pink.
        /// </summary>
        internal static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Salmon.
        /// </summary>
        internal static string LightSalmon {
            get {
                return ResourceManager.GetString("LightSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Sea Green.
        /// </summary>
        internal static string LightSeaGreen {
            get {
                return ResourceManager.GetString("LightSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Sky Blue.
        /// </summary>
        internal static string LightSkyBlue {
            get {
                return ResourceManager.GetString("LightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Slate Gray.
        /// </summary>
        internal static string LightSlateGray {
            get {
                return ResourceManager.GetString("LightSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Steel Blue.
        /// </summary>
        internal static string LightSteelBlue {
            get {
                return ResourceManager.GetString("LightSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Light Yellow.
        /// </summary>
        internal static string LightYellow {
            get {
                return ResourceManager.GetString("LightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lime.
        /// </summary>
        internal static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lime Green.
        /// </summary>
        internal static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Linen.
        /// </summary>
        internal static string Linen {
            get {
                return ResourceManager.GetString("Linen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Maroon.
        /// </summary>
        internal static string Maroon {
            get {
                return ResourceManager.GetString("Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Aquamarine.
        /// </summary>
        internal static string MediumAquamarine {
            get {
                return ResourceManager.GetString("MediumAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Blue.
        /// </summary>
        internal static string MediumBlue {
            get {
                return ResourceManager.GetString("MediumBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Orchid.
        /// </summary>
        internal static string MediumOrchid {
            get {
                return ResourceManager.GetString("MediumOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Purple.
        /// </summary>
        internal static string MediumPurple {
            get {
                return ResourceManager.GetString("MediumPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Sea Green.
        /// </summary>
        internal static string MediumSeaGreen {
            get {
                return ResourceManager.GetString("MediumSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Slate Blue.
        /// </summary>
        internal static string MediumSlateBlue {
            get {
                return ResourceManager.GetString("MediumSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Spring Green.
        /// </summary>
        internal static string MediumSpringGreen {
            get {
                return ResourceManager.GetString("MediumSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Turquoise.
        /// </summary>
        internal static string MediumTurquoise {
            get {
                return ResourceManager.GetString("MediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Medium Violet Red.
        /// </summary>
        internal static string MediumVioletRed {
            get {
                return ResourceManager.GetString("MediumVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Midnight Blue.
        /// </summary>
        internal static string MidnightBlue {
            get {
                return ResourceManager.GetString("MidnightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mint Cream.
        /// </summary>
        internal static string MintCream {
            get {
                return ResourceManager.GetString("MintCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Misty Rose.
        /// </summary>
        internal static string MistyRose {
            get {
                return ResourceManager.GetString("MistyRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Moccasin.
        /// </summary>
        internal static string Moccasin {
            get {
                return ResourceManager.GetString("Moccasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Navajo White.
        /// </summary>
        internal static string NavajoWhite {
            get {
                return ResourceManager.GetString("NavajoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Navy.
        /// </summary>
        internal static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Old Lace.
        /// </summary>
        internal static string OldLace {
            get {
                return ResourceManager.GetString("OldLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Olive.
        /// </summary>
        internal static string Olive {
            get {
                return ResourceManager.GetString("Olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Olive Drab.
        /// </summary>
        internal static string OliveDrab {
            get {
                return ResourceManager.GetString("OliveDrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Orange Red.
        /// </summary>
        internal static string OrangeRed {
            get {
                return ResourceManager.GetString("OrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Orchid.
        /// </summary>
        internal static string Orchid {
            get {
                return ResourceManager.GetString("Orchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pale EasyITCenterrod.
        /// </summary>
        internal static string PaleEasyITCenterrod {
            get {
                return ResourceManager.GetString("PaleEasyITCenterrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pale Green.
        /// </summary>
        internal static string PaleGreen {
            get {
                return ResourceManager.GetString("PaleGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pale Turquoise.
        /// </summary>
        internal static string PaleTurquoise {
            get {
                return ResourceManager.GetString("PaleTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pale Violet Red.
        /// </summary>
        internal static string PaleVioletRed {
            get {
                return ResourceManager.GetString("PaleVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Papaya Whip.
        /// </summary>
        internal static string PapayaWhip {
            get {
                return ResourceManager.GetString("PapayaWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Peach Puff.
        /// </summary>
        internal static string PeachPuff {
            get {
                return ResourceManager.GetString("PeachPuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Peru.
        /// </summary>
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Plum.
        /// </summary>
        internal static string Plum {
            get {
                return ResourceManager.GetString("Plum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Powder Blue.
        /// </summary>
        internal static string PowderBlue {
            get {
                return ResourceManager.GetString("PowderBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rosy Brown.
        /// </summary>
        internal static string RosyBrown {
            get {
                return ResourceManager.GetString("RosyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Royal Blue.
        /// </summary>
        internal static string RoyalBlue {
            get {
                return ResourceManager.GetString("RoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Saddle Brown.
        /// </summary>
        internal static string SaddleBrown {
            get {
                return ResourceManager.GetString("SaddleBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Salmon.
        /// </summary>
        internal static string Salmon {
            get {
                return ResourceManager.GetString("Salmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sandy Brown.
        /// </summary>
        internal static string SandyBrown {
            get {
                return ResourceManager.GetString("SandyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sea Green.
        /// </summary>
        internal static string SeaGreen {
            get {
                return ResourceManager.GetString("SeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sea Shell.
        /// </summary>
        internal static string SeaShell {
            get {
                return ResourceManager.GetString("SeaShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sienna.
        /// </summary>
        internal static string Sienna {
            get {
                return ResourceManager.GetString("Sienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sky Blue.
        /// </summary>
        internal static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Slate Blue.
        /// </summary>
        internal static string SlateBlue {
            get {
                return ResourceManager.GetString("SlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Slate Gray.
        /// </summary>
        internal static string SlateGray {
            get {
                return ResourceManager.GetString("SlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Snow.
        /// </summary>
        internal static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Spring Green.
        /// </summary>
        internal static string SpringGreen {
            get {
                return ResourceManager.GetString("SpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Steel Blue.
        /// </summary>
        internal static string SteelBlue {
            get {
                return ResourceManager.GetString("SteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tan.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Teal.
        /// </summary>
        internal static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Thistle.
        /// </summary>
        internal static string Thistle {
            get {
                return ResourceManager.GetString("Thistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tomato.
        /// </summary>
        internal static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Turquoise.
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Violet.
        /// </summary>
        internal static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Wheat.
        /// </summary>
        internal static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný White Smoke.
        /// </summary>
        internal static string WhiteSmoke {
            get {
                return ResourceManager.GetString("WhiteSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yellow Green.
        /// </summary>
        internal static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
    }
}
